-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN "ocrEngine" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Invoice" ADD COLUMN "ocrRawText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Invoice" ADD COLUMN "pageCount" INTEGER NOT NULL DEFAULT 0;
